apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudwatch-config
  namespace: redemption
data:
  cwagentconfig.json: |
    {
      "logs": {
        "logs_collected": {
          "files": {
            "collect_list": [
              {
                "file_path": "/var/log/containers/redemption-service*",
                "log_group_name": "/eks/redemption-prod/app/redemption",
                "log_stream_name": "{hostname}/{container_name}",
                "timezone": "UTC"
              }
            ]
          }
        },
        "force_flush_interval": 5
      }
    }
